### ISSUE TITLE
Optimizar cálculo del vector hipótetico en la función importwimp()

### ISSUE THREAD

**Issue by Asanfe** [GICUNED/GridFCM.practicum#8]
Actualmente se utiliza un bucle for para calcular el vector del yo hipotético. Hay que darle una vuelta para que se calcule con una función de tipo apply y asi optimizar la computación del cálculo.

El código actual es: 
```
standarized.hypothetical <- rep(0,n.constructs)
  n <- 1
  for (i in standarized.self) {
    if(i != 0){
      standarized.hypothetical[n] <- standarized.self[n] / (-1 * abs(standarized.self[n]))
    }
    if(i == 0 && !(0 %in% standarized.ideal[n])){
      standarized.hypothetical[n] <- standarized.ideal[n] / abs(standarized.ideal[n])
    }
    if(i == 0 && (0 %in% standarized.ideal[n])){
      standarized.hypothetical[n] <- 1
    }
    n <- n + 1
  }
```

**Comment by churtado-gh** [comment]
Hola. Envío una propuesta para eliminar el bucle con un _mapply_:

\# Función a aplicar en ambos vectores, elemento a elemento
calc_standr_hypothetical <- function(elem.self, elem.ideal) {
&emsp;if (elem.self != 0) {
&emsp;&emsp;return(elem.self / (-1 * abs(elem.self)))

&emsp;} else if (elem.self == 0 && !(0 %in% elem.ideal)) {
&emsp;&emsp;return(elem.ideal / abs(elem.ideal))

&emsp;} else if (elem.self == 0 && (0 %in% elem.ideal)) {
&emsp;&emsp;return(1)
&emsp;}
}

\# Aplicamos la función utilizando mapply (se cuenta con que ambos vectores tienen la misma longitud)
standarized.hypothetical <- mapply(calc_standr_hypothetical , standarized.self, standarized.ideal)

**Comment by Fgil77** [comment]
Grande Carlos, lo he sustituido en la función importwimp y funciona.  

Estaba enfrascado intentándolo, me devolvía el vector que esperaba, pero dentro de la función importfuntions no se ejecutaba correctamente, me faltaba el concepto del mapply. 
Muchas gracias, vamos intentando pillar algo...

**Comment by Asanfe** [comment]
Muchas gracias por el código, si queréis implementarlo en la función y subirlo al repositorio adelante!

Si estáis más liados con el tema de centralidad, me puedo encargar yo de implementar el código que ha puesto @churtado-gh y subirlo. Decidme con lo que sea.

**Comment by Asanfe** [comment]
Ya está subido el nuevo código al repositorio con la función mapply().

**Comment by churtado-gh** [comment]
Genial!
